### ISSUE TITLE
CCT for NLP

### ISSUE THREAD

**Issue by stevemarin** [SHI-Labs/Compact-Transformers#15]
This is very exciting!  Thank you!  I'm interested in exploring this with NLP.  Unfortunately, I'm running into some issues that seem to be related to expected tensor sizes when running one of your models.  Do you have any extra NLP-related materials/training scripts that you can share?

**Comment by alihassanijr** [comment]
Thank you for your interest. Yes, the NLP scripts are not yet released, we're working on that. It should be out within a few days, along with the checkpoints.

**Comment by alihassanijr** [comment]
Hello again,
The last commit added the text variants we used for text classification (Table 3 in the latest preprint).
We'll release the checkpoints soon.

**Comment by stevemarin** [comment]
I can't wait.  Thank you very much!

**Comment by alihassanijr** [comment]
I uploaded the checkpoints for AGNews and TREC. I want to mention that due to a checkpoint saving issue some of the numbers may be different from what we reported, we're currently re-running those. We decided to upload because the differences are very little.
I'm also closing the issue now, if you still have questions feel free to open it back up.
