### ISSUE TITLE
About image size

### ISSUE THREAD

**Issue by Booooooooooo** [SHI-Labs/Compact-Transformers#16]
Thank you for your dedication. 
You mentioned that changing images sizes will affect the sequence length. Can CCT take inputs with various image sizes? For example, if I've trained CCT with image_size = 256x256. Can I test this CCT on images with size 512x512?

**Comment by alihassanijr** [comment]
Thank you for your interest.
Technically, as long as there's a learnable positional embedding, it literally limits the ability to use higher resolutions, because the sequence length changes (this holds true for most vision transformers). Also, in the paper we explore changing resolutions with different PEs, and see the effect each has on performance.
There is one option, which is widely practiced for ImageNet, and that is training on 224x224 images, and then fine-tuning (including a new PE) on higher resolutions, and that is shown to have better performance. The reason why you would do this is to pretrain faster, and later fine-tune on the higher resolution.
To be clear, both ViT and CCT will have a different sequence length depending on the resolution of the input image, and changing the resolution after training just for the purpose of inference faces changes in performance, and as long as your PE is learnable, it would be a fixed size (for smaller images you can pad with zeros, larger images are more difficult to deal with).

**Comment by Booooooooooo** [comment]
Thank you very much~
