### ISSUE TITLE
Train on Custom dataset ? 

### ISSUE THREAD

**Issue by samsu007** [SHI-Labs/Compact-Transformers#17]
if we have set of image folders  how to train on this type of datasets ?

**Comment by alihassanijr** [comment]
Hi, the training script that's in place is an example. You can just edit it and change the dataset lines with ImageFolder instead of CIFAR10/100. You can also use other reference training scripts. We recommend [timm's reference training script](https://github.com/rwightman/pytorch-image-models/blob/master/train.py).

**Comment by samsu007** [comment]
thanks man. it helps a lot
