### ISSUE TITLE
Difference between Hybrid Vit, CCT and CVT

### ISSUE THREAD

**Issue by Yeez-lee** [SHI-Labs/Compact-Transformers#18]
Hi, It's a nice work. But I still feel little bit confused about some points.
(1) To make the ViT still effective for small data, CCT and CVT modify the tokenization part.  And CVT applies patching while CCT uses the convolution. Is my understanding correct? 
(2) In the original Vit paper, they use Hybrid Vit to do the investigation and comparison. So, your method still belongs to Hybrid Vit and CCT is more similar to Hybrid Vit, right? Did you compare yours with the original Hybrid Vit? It seems that I didn't see it in your paper. BTW, I just want to make sure that the convolution (ResNet) of the original Hybrid Vit is also training along with Vit ,right?

Thanks for help!

**Comment by alihassanijr** [comment]
Hi,
Thank you for your interest.
(1) No, CVT does not modify the tokenization step. It only applies sequence pooling instead of using a class token.
(2) Technically, the hybrid model is a combination of a ResNet backbone and ViT (**along with the patch tokenization**), ours is just one or two blocks containing a convolution, activation, and maxpool **instead of the patch tokenization**. ViT variants proposed in the original paper are big enough to overfit datasets as small as CIFAR-10 which was the problem, and the hybrid models are even larger, so it would probably not help improve generalization there. And yes, everything is trained, nothing is pre-trained and frozen in the image models.

**Comment by alihassanijr** [comment]
I'm closing the issue now, if you still have questions feel free to open it back up.
