### ISSUE TITLE
Fine-tune with customs dataset 

### ISSUE THREAD

**Issue by ogahozy** [SHI-Labs/Compact-Transformers#20]
Great work
How can I use custom dataset on your model.

**Comment by alihassanijr** [comment]
Thank you for your interest.
As I mentioned in #17 , the training script that's in place is an example. You can just edit it and change the dataset class with ImageFolder instead of CIFAR10/100. You can also use other reference training scripts. We recommend timm's reference training script.
As for fine-tuning, you might have to edit further to load a checkpoint first, and then the details are up to you on how exactly you want to fine-tune.
You can just fine-tune the final classifier (the fc layer), positional embedding (if learnable and if you want to use different sized images than the original), and other parts of the network as well. It really depends on what you want to fine-tune on.

**Comment by ogahozy** [comment]
Thanks

ogahozy

**Comment by alihassanijr** [comment]
I'm closing the issue now. If you still have questions feel free to open it back up.
