### ISSUE TITLE
In the model_urls that you gave the pretrained model's paths, I don't understand some keys like the 't' in 'cct14t-7x2' or '_sine'. What does it mean?

### ISSUE THREAD

**Issue by xuritian317** [SHI-Labs/Compact-Transformers#38]

**Comment by alihassanijr** [comment]
Hello,
Thank you for your interest.
The `t` from `CCT-14t` is from a very early version of the paper, and has been changed to `CCT-14`.
We noticed that it's still there in the README by mistake, that will be corrected, and we thank you for bringing this to our attention.
`sine` means sinusoidal positional embedding was used instead of learnable ones.

If you have any more questions feel free to reopen this issue.
