### ISSUE TITLE
Creating custom model

### ISSUE THREAD

**Issue by iliasprc** [SHI-Labs/Compact-Transformers#40]
Hello I have made a different file `custom_vit.py` under src folder and I have created my model.
However I am getting the following error

Traceback (most recent call last):
  File "/home/iliask/PycharmProjects/Compact-Transformers/train.py", line 806, in <module>
    main()
  File "/home/iliask/PycharmProjects/Compact-Transformers/train.py", line 357, in main
    model = create_model(
  File "/home/iliask/miniconda3/envs/SLVTP/lib/python3.9/site-packages/timm/models/factory.py", line 79, in create_model
    raise RuntimeError('Unknown model (%s)' % model_name)
RuntimeError: Unknown model (custom_vit_2_4_32)

**Comment by alihassanijr** [comment]
Hi,
Thank you for your interest. This is because you probably haven't registered your model, or haven't imported it.
For instance:
https://github.com/SHI-Labs/Compact-Transformers/blob/e6869b4326e252bf9d6c1e5439ab824f2f4d7f2a/src/vit.py#L169-L177

And you have to import the decorator from `timm`:
https://github.com/SHI-Labs/Compact-Transformers/blob/e6869b4326e252bf9d6c1e5439ab824f2f4d7f2a/src/vit.py#L7-L10

(Side note: the reason for the exception handling is in case some doesn't want to use `timm` and doesn't have the package. Our models are in pure PyTorch, but our recommended training script is `timm`'s.)

And I assume you either imported `custom_vit` within the package in `__init__.py`:
https://github.com/SHI-Labs/Compact-Transformers/blob/e6869b4326e252bf9d6c1e5439ab824f2f4d7f2a/src/__init__.py#L1-L3

Or at least manually into the training script:
https://github.com/SHI-Labs/Compact-Transformers/blob/e6869b4326e252bf9d6c1e5439ab824f2f4d7f2a/train.py#L41

Please let me know if this solves your issue.

**Comment by iliasprc** [comment]
Hi and thanks for the fast reply, I have registered the models and imported them on   `__init__.py`
However, as I found out they are not included in the list create_model function that has all the models from timm library and your models (cct, cvt vit)

**Comment by alihassanijr** [comment]
Could you link me to your repository? Registering the model and making sure it's imported is enough.

**Comment by stevenwalton** [comment]
Hey @iliasprc, is this for your [Masters Thesis?](https://github.com/iliasprc/MScThesis/blob/main/idp_programs/dnn/cct.py). I noticed you're using the NLP version of the model and not the vision version. You might notice some slight differences between them (as @alihassanijr highlights above). You'll notice in the [NLP README](https://github.com/SHI-Labs/Compact-Transformers/blob/main/nlp/README.md) that we do a different call (not using timm). I think we could make this less confusing. Maybe we should add the timm part. What do you think Ali?

**Comment by iliasprc** [comment]
Hi , I solved the problem. I was importing the register function from the repo instead of the function of timm.
That solved the issue, Thanks for your feedback.
