### ISSUE TITLE
please close this.

### ISSUE THREAD

**Issue by yuedajiong** [SHI-Labs/Compact-Transformers#84]

**Comment by stevenwalton** [comment]
You can paste code into the issue or `0x0.st` is a fine place to upload the file. But without more context the comment comes off indistinguishable from a bot.

**Comment by yuedajiong** [comment]
@stevenwalton   thanks
I uploaded my simplified code here, based on you guys' code.
your algorithm is very powerful.

**Comment by stevenwalton** [comment]
There are multiple ways to contribute.

- Submit a PR
- Show and discuss your code here
- If you would like it to be temporary, upload it to [https://0x0.st](https://0x0.st) where I can read it without downloading it

But do not upload the file as this poses a security risk. The PR is the best way to submit because we can compare things line by line and perform code review.

But it is also not clear to me what you are trying to do and why. Did you improve something? Did you just simplify code?

**Comment by stevenwalton** [comment]
You can always press the close issue without needing to change the title
